README.md, app_sidebar_collapsible.py, docker-compose-prod-nginx.yml, docker/ngnix.conf
- Check in a simple docker-compose to run the app behind an ngnix proxy
- Set the relative path prefix to `/admin/`
- change all the hrefs to use relative paths
=> Support and test the reverse proxy configuration

utils/constants.py, utils/db_utils.py
This is a hack to get the dashboard to work.
It retrieves data using the timeseries interfaces and performs the projections using pandas locally.
It is *not* complete.
Notably:
- the projections are not the same as the original projections
- the projections do not take the dynamic config into account
- we still use `edb` for some calls - notably the ones to get the uuid table; we should add decorations to the timeseries to support them going forward
This is a partial fix for https://github.com/e-mission/op-admin-dashboard/issues/29
=> Hack to use the timeseries calls to retrieve the data

pages/data.py, utils/constants.py, utils/db_utils.py, utils/permissions.py
Using time series queries to address https://github.com/e-mission/op-admin-dashboard/issues/29
=> Timeseries query

app_sidebar_collapsible.py, pages/map.py, requirements.txt
The CSP has multiple limitations:
- uses `unsafe-inline` - I tried the nonce and it didn't work
- puts everything into `default-src`
Filed issue to have the template fixed
https://github.com/NREL/nrel-app-template-bootstrap4/issues/16
=> :lock: implement a basic CSP so that we can pass the WAVA scan

utils/permissions.py
Show data tables if the dynamic config does not have the admin_dashboard.
This should address https://github.com/e-mission/op-admin-dashboard/issues/46.
=> data tables invisibility

pages/data.py, utils/constants.py, utils/db_utils.py
This pull request is going to address this issue: https://github.com/e-mission/op-admin-dashboard/issues/48
=> Add some trip stats to the user screen

docker/Dockerfile
Fixed base image for server after addressing latest vulnerabilities in [this PR](https://github.com/e-mission/e-mission-server/pull/943).
Updated docker image tag so dashboard can pull from the latest base server image.
=> Update Docker image tag

app_sidebar_collapsible.py, pages/data.py, pages/home.py, requirements.txt, utils/datetime_utils.py, utils/db_utils.py
> On the initial load, the user has not selected a date and we fallback to only showing the last week of data. The datepicker should convey this information rather than showing blank initially.
> 
> This change sets initial start and end date values to the datepicker. As a result, we will no longer need extra checks for the initial condition when start date or end date have not been set yet. This simplifies the code in a few places.
> Consider "1/5/2024" – in the US this seems like January 5, while in most of the world it seems like May 1. Whether we did D/M/Y or M/D/Y, it'd probably cause some confusion since the project is used on an international scale.
> 
> So instead of just digits, the new format will be "5 Jan 2024". Unambiguous and still pretty concise.
>
=> 📅 Datepicker: set initial range, use unambiguous date format, use `arrow`, dropdown for `timezone` option

pages/home.py
After our recent updates, the trip trends on the Home tab aren't working. The error occurs when the column data is converted to `datetime` with a specific format (ISO8601).
=> [Bug fix] Trips trend on Home not working

pages/map.py
The current map page shows the map feature even though there is no trip data, which can appear as a bug to users. To prevent confusion, I added the 'no data' text when there is no trip data instead of displaying an empty map.
<br />
[ No trip data ]
=> Map - show map only when there is trip data

app_sidebar_collapsible.py
We had a single checkbox to exclude test users, which worked fine for that purpose. But for programs with multiple subgroups we want to be able to filter by any of the subgroups
I modified this into a multi dropdown which has all subgroups from the config (or just 'test' if the config doesn't define subgroups)
I also made the default value reflect metrics.include_test_users from the config.
=> expand filters to be able to exclude any subgroup(s)

app_sidebar_collapsible.py, pages/data.py, utils/constants.py, utils/db_utils.py, utils/permissions.py
…rip table
My original thought was that this would be a simple 2-3 line change where I would enable the cleaned/inferred mode summaries in the set of valid columns.
However, while actually implementing it, I ran into several issues:
1. we display the primary sensed mode in the public dashboard, so we can't just display the summary, we have to extract the primary mode
2. I then switched to using the primary mode computation from the public dashboard, only to discover that it needs the summary as an object.  However, the previous implementation of this code used `pd.json_normalize`, which resulted in columns like
```
'data.inferred_section_summary.distance.TRAIN',
'data.inferred_section_summary.duration.TRAIN',
'data.inferred_section_summary.count.TRAIN', …
```
=> ✨ Incorporate the sensed/inferred/BLE sensed primary modes and survey results

README.md
Updating docs to reference changes from the Redesign PR #113 
These mostly involve removal of config-fake.py and config.py file that contained the CognitoConfig class for setting AWS Cognito credentials.
We now set the values directly via Environment variables.
=> Updating Readme - Using environment variables for AWS Cognito

.gitignore, docker-compose-dev.yml, pages/data.py, utils/db_utils.py
A toggle has been added to the "Trajectories" tab in the admin dashboard. This will allow administrators to switch between viewing "Analysis/Recreated Location" data and raw "Background/Location" data. The toggle is initially hidden and only visible when the "Trajectories" tab is active.
This change is a high-priority temporary measure to restore functionality to UUE's admin dashboard. It enables them to access raw trajectory data, ensuring they remain unblocked while a more permanent solution is being worked on.
- Verified that the toggle switch properly switches between the two data views.
=> UUE Temp Fix

pages/data.py, pages/home.py, utils/db_utils.py
This pull request introduces a temporary logging setup to enhance debugging and monitor function execution times until the logging mechanism can be fully integrated into the emission server.
- Configured the logging system to capture all log levels with detailed formatting.
- Implemented a `log_execution_time` decorator to log the start and end times of function executions.
=> Temporary Logging

pages/data.py, utils/db_utils.py
- **Reverted to Baseline**
- Rolled back previous batching changes to establish a stable performance baseline.
- **Implemented Baseline Logging**
- Logging to `add_user_stats` and `render_content`
- **Reversion Verification**
- Confirmed that all batching changes have been successfully reverted.
- Ensured no new issues or regressions were introduced by the reversion* (TBD).
- Part of [#141](https://github.com/your-repo/issues/141) - Temporary Logging
- Part of [Project Plan](https://github.com/e-mission/op-admin-dashboard/issues/145) - Baseline Setup #145 
- This PR establishes the baseline necessary for assessing the impact of future batching and performance improvements.
=> Reverted #124 and Added Logging

utils/constants.py, utils/db_utils.py, utils/permissions.py
Enhances the user profile data retrieval process by incorporating newly stored statistics (`pipeline_range`, `total_trips`, `labeled_trips`, and `last_call`) into the existing `with` block. These statistics are now seamlessly integrated into the `user` dictionary, providing a more comprehensive set of user metrics for further analysis and dashboard visualization.
- **Existing Functionality**:
- The `with` block previously retrieved basic profile information such as `platform`, `manufacturer`, `app_version`, `os_version`, and `phone_lang` from the database and assigned them to the `user` dictionary.
- **New Enhancements**:
- **Pipeline Range**:
- Retrieved `pipeline_range` data, including `start_ts` and `end_ts`, to understand the timeframe of the user's activity pipeline.
- **Trip …
=>  Integrate New User Statistics into Profile Retrieval

pages/home.py
This PR refactors the process for retrieving the last API call timestamps to significantly improve performance. The previous implementation relied on a complex aggregation pipeline, which has been replaced with a simpler, iterative approach using profile db like previous enhancements.
- **Improved Performance:** Reduces database load and speeds up the retrieval process.
- **Simplified Logic:** Enhances maintainability and readability of the code.
- **Scalability:** Handles larger datasets more efficiently.
The changes result in faster execution and lower computational costs, particularly for scenarios with large user datasets like openaccess.
- Tested by loading a dataset and seeing the overview page's `Active Users`
- Logging checks
- Do we have a way to manually make something an active …
=> Refactored retrieval of last API call timestamps to improve performance.

pages/data.py
We should only show "allowed_trip_columns" + userinputcols, not "all_trip_columns"
Regression from f357d6a7235d8b8a045e68063235104a5f090b9b
=> 🚑 fix excluded columns showing on trips table

docker/load_mongodump.sh
Restores the changes made to the `docker/load_mongodump.sh` file that seem to have been overwritten during a rebase. 
Additionally, this PR incorporates the necessary changes from [e-mission/em-public-dashboard#163](https://github.com/e-mission/em-public-dashboard/pull/163), ensuring consistency across repositories and minimizing the need for manual edits in the future.
- Restored the missing changes in `load_mongodump.sh`.
- Synced adjustments from `em-public-dashboard` to address [op-admin-dashboard#122 (comment)](https://github.com/e-mission/op-admin-dashboard/issues/122#issuecomment).
- Fixes [op-admin-dashboard#122](https://github.com/e-mission/op-admin-dashboard/issues/122).
- Reference to changes from [em-public-dashboard#163](https://github.com/e-mission/em-public-dashboard/pull/16 …
=> Restore Changes to `load_mongodump.sh` and Sync with `em-public-dashboard`
